### Product Index Action
GET http://localhost:3000/products.json 

### Product Show Action
GET http://localhost:3000/products/1.json 

### Product Create Action
POST http://localhost:3000/products.json 
Content-Type: application/json

{
  "name": "testName: check for image error",
  "price": 8,
  "description": "this is the test-description",
  "image_url": "test.png"

}

### Product Update Action
PATCH http://localhost:3000/products/7.json 
Content-Type: application/json

{
   "name": "test name",
  "price": 1,
  "image_url": "test url",
  "description": "test description"
}

### Product Destory Action
DELETE http://localhost:3000/products/2.json 

### supplier Index Action
GET http://localhost:3000/suppliers.json 

### supplier Show Action
GET http://localhost:3000/suppliers/1.json 

### Supplier Create Action
POST http://localhost:3000/suppliers.json 
Content-Type: application/json

{
  "name": "testName2",
  "email": "test2@email.com",
  "phone_number": "211111111"

}